name = "nustology-prep"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "nustology-db"
database_id = "fda742a1-207b-4bd6-8345-2ac57228a329"
